name: macos-dmg
on:
  push:
    branches:
      - main
      - feature/*
      - feat/*
    tags:
      - v*
  release:
    types:
      - published
jobs:
  package:
    runs-on: macos-latest
    steps:
      - name: Chekcout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install devenv
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use devenv
          nix-env -if https://github.com/cachix/devenv/tarball/v0.4
      - name: Yarn init
        run: |
          eval "$(devenv print-dev-env)"
          yarn
      - name: Set tag as app version
        if: github.event_name == 'release'
        run: |
          eval "$(devenv print-dev-env)"
          yarn version --no-git-tag-version --new-version "${{ github.event.release.tag_name }}"
      - name: Build DMG
        run: |
          eval "$(devenv print-dev-env)"
          yarn make --targets '@electron-forge/maker-dmg'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dmg
          path: ./out/make/*.dmg
      - name: Add DMG to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/make/*.dmg
