name: windows-squirrel
on:
  push:
    branches:
      - main
      - feature/*
      - feat/*
    tags-ignore:
      - v*
  release:
    types:
      - published
jobs:
  package:
    # only run for releases with v* tags
    if: github.event_name != 'release' || startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install devenv
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use devenv
          nix-env -if https://github.com/cachix/devenv/tarball/v0.5
      - name: Yarn init
        run: |
          eval "$(devenv print-dev-env)"
          yarn
      - name: Set tag as app version
        if: github.event_name == 'release'
        run: |
          eval "$(devenv print-dev-env)"
          yarn version --no-git-tag-version --new-version "${{ github.event.release.tag_name }}"
      - name: Build Squirrel Installer
        run: |
          eval "$(devenv print-dev-env)"
          yarn make -p win32 -a x64
      - name: Upload artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: windows-squirrel
          path: ./out/make/squirrel.windows/*/*.exe
      - name: Add to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/make/squirrel.windows/*/*.exe
